/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as InvitationsIdRouteImport } from './routes/invitations.$id'
import { Route as TTenantRouteImport } from './routes/t.$tenant'
import { Route as TTenantIndexRouteImport } from './routes/t.$tenant.index'
import { Route as TTenantSettingsRouteImport } from './routes/t.$tenant.settings'
import { Route as TTenantPProjectRouteImport } from './routes/t.$tenant.p.$project'
import { Route as TTenantPProjectIndexRouteImport } from './routes/t.$tenant.p.$project.index'
import { Route as TTenantPProjectEditorRouteImport } from './routes/t.$tenant.p.$project.editor'
import { Route as TTenantPProjectFilesRouteImport } from './routes/t.$tenant.p.$project.files'
import { Route as TTenantPProjectSettingsRouteImport } from './routes/t.$tenant.p.$project.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsIdRoute = InvitationsIdRouteImport.update({
  id: '/invitations/$id',
  path: '/invitations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantRoute = TTenantRouteImport.update({
  id: '/t/$tenant',
  path: '/t/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantIndexRoute = TTenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantSettingsRoute = TTenantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantPProjectRoute = TTenantPProjectRouteImport.update({
  id: '/p/$project',
  path: '/p/$project',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantPProjectIndexRoute = TTenantPProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantPProjectRoute,
} as any)
const TTenantPProjectEditorRoute = TTenantPProjectEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => TTenantPProjectRoute,
} as any)
const TTenantPProjectFilesRoute = TTenantPProjectFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => TTenantPProjectRoute,
} as any)
const TTenantPProjectSettingsRoute = TTenantPProjectSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TTenantPProjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/invitations/$id': typeof InvitationsIdRoute
  '/t/$tenant': typeof TTenantRouteWithChildren
  '/compare/': typeof CompareIndexRoute
  '/t/$tenant/settings': typeof TTenantSettingsRoute
  '/t/$tenant/': typeof TTenantIndexRoute
  '/t/$tenant/p/$project': typeof TTenantPProjectRouteWithChildren
  '/t/$tenant/p/$project/editor': typeof TTenantPProjectEditorRoute
  '/t/$tenant/p/$project/files': typeof TTenantPProjectFilesRoute
  '/t/$tenant/p/$project/settings': typeof TTenantPProjectSettingsRoute
  '/t/$tenant/p/$project/': typeof TTenantPProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/invitations/$id': typeof InvitationsIdRoute
  '/compare': typeof CompareIndexRoute
  '/t/$tenant/settings': typeof TTenantSettingsRoute
  '/t/$tenant': typeof TTenantIndexRoute
  '/t/$tenant/p/$project/editor': typeof TTenantPProjectEditorRoute
  '/t/$tenant/p/$project/files': typeof TTenantPProjectFilesRoute
  '/t/$tenant/p/$project/settings': typeof TTenantPProjectSettingsRoute
  '/t/$tenant/p/$project': typeof TTenantPProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/invitations/$id': typeof InvitationsIdRoute
  '/t/$tenant': typeof TTenantRouteWithChildren
  '/compare/': typeof CompareIndexRoute
  '/t/$tenant/settings': typeof TTenantSettingsRoute
  '/t/$tenant/': typeof TTenantIndexRoute
  '/t/$tenant/p/$project': typeof TTenantPProjectRouteWithChildren
  '/t/$tenant/p/$project/editor': typeof TTenantPProjectEditorRoute
  '/t/$tenant/p/$project/files': typeof TTenantPProjectFilesRoute
  '/t/$tenant/p/$project/settings': typeof TTenantPProjectSettingsRoute
  '/t/$tenant/p/$project/': typeof TTenantPProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/compare/$slug'
    | '/invitations/$id'
    | '/t/$tenant'
    | '/compare/'
    | '/t/$tenant/settings'
    | '/t/$tenant/'
    | '/t/$tenant/p/$project'
    | '/t/$tenant/p/$project/editor'
    | '/t/$tenant/p/$project/files'
    | '/t/$tenant/p/$project/settings'
    | '/t/$tenant/p/$project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/compare/$slug'
    | '/invitations/$id'
    | '/compare'
    | '/t/$tenant/settings'
    | '/t/$tenant'
    | '/t/$tenant/p/$project/editor'
    | '/t/$tenant/p/$project/files'
    | '/t/$tenant/p/$project/settings'
    | '/t/$tenant/p/$project'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/compare/$slug'
    | '/invitations/$id'
    | '/t/$tenant'
    | '/compare/'
    | '/t/$tenant/settings'
    | '/t/$tenant/'
    | '/t/$tenant/p/$project'
    | '/t/$tenant/p/$project/editor'
    | '/t/$tenant/p/$project/files'
    | '/t/$tenant/p/$project/settings'
    | '/t/$tenant/p/$project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  CompareSlugRoute: typeof CompareSlugRoute
  InvitationsIdRoute: typeof InvitationsIdRoute
  TTenantRoute: typeof TTenantRouteWithChildren
  CompareIndexRoute: typeof CompareIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$id': {
      id: '/invitations/$id'
      path: '/invitations/$id'
      fullPath: '/invitations/$id'
      preLoaderRoute: typeof InvitationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenant': {
      id: '/t/$tenant'
      path: '/t/$tenant'
      fullPath: '/t/$tenant'
      preLoaderRoute: typeof TTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenant/': {
      id: '/t/$tenant/'
      path: '/'
      fullPath: '/t/$tenant/'
      preLoaderRoute: typeof TTenantIndexRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/settings': {
      id: '/t/$tenant/settings'
      path: '/settings'
      fullPath: '/t/$tenant/settings'
      preLoaderRoute: typeof TTenantSettingsRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/p/$project': {
      id: '/t/$tenant/p/$project'
      path: '/p/$project'
      fullPath: '/t/$tenant/p/$project'
      preLoaderRoute: typeof TTenantPProjectRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/p/$project/': {
      id: '/t/$tenant/p/$project/'
      path: '/'
      fullPath: '/t/$tenant/p/$project/'
      preLoaderRoute: typeof TTenantPProjectIndexRouteImport
      parentRoute: typeof TTenantPProjectRoute
    }
    '/t/$tenant/p/$project/editor': {
      id: '/t/$tenant/p/$project/editor'
      path: '/editor'
      fullPath: '/t/$tenant/p/$project/editor'
      preLoaderRoute: typeof TTenantPProjectEditorRouteImport
      parentRoute: typeof TTenantPProjectRoute
    }
    '/t/$tenant/p/$project/files': {
      id: '/t/$tenant/p/$project/files'
      path: '/files'
      fullPath: '/t/$tenant/p/$project/files'
      preLoaderRoute: typeof TTenantPProjectFilesRouteImport
      parentRoute: typeof TTenantPProjectRoute
    }
    '/t/$tenant/p/$project/settings': {
      id: '/t/$tenant/p/$project/settings'
      path: '/settings'
      fullPath: '/t/$tenant/p/$project/settings'
      preLoaderRoute: typeof TTenantPProjectSettingsRouteImport
      parentRoute: typeof TTenantPProjectRoute
    }
  }
}

interface TTenantPProjectRouteChildren {
  TTenantPProjectEditorRoute: typeof TTenantPProjectEditorRoute
  TTenantPProjectFilesRoute: typeof TTenantPProjectFilesRoute
  TTenantPProjectSettingsRoute: typeof TTenantPProjectSettingsRoute
  TTenantPProjectIndexRoute: typeof TTenantPProjectIndexRoute
}

const TTenantPProjectRouteChildren: TTenantPProjectRouteChildren = {
  TTenantPProjectEditorRoute: TTenantPProjectEditorRoute,
  TTenantPProjectFilesRoute: TTenantPProjectFilesRoute,
  TTenantPProjectSettingsRoute: TTenantPProjectSettingsRoute,
  TTenantPProjectIndexRoute: TTenantPProjectIndexRoute,
}

const TTenantPProjectRouteWithChildren = TTenantPProjectRoute._addFileChildren(
  TTenantPProjectRouteChildren,
)

interface TTenantRouteChildren {
  TTenantSettingsRoute: typeof TTenantSettingsRoute
  TTenantIndexRoute: typeof TTenantIndexRoute
  TTenantPProjectRoute: typeof TTenantPProjectRouteWithChildren
}

const TTenantRouteChildren: TTenantRouteChildren = {
  TTenantSettingsRoute: TTenantSettingsRoute,
  TTenantIndexRoute: TTenantIndexRoute,
  TTenantPProjectRoute: TTenantPProjectRouteWithChildren,
}

const TTenantRouteWithChildren =
  TTenantRoute._addFileChildren(TTenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  CompareSlugRoute: CompareSlugRoute,
  InvitationsIdRoute: InvitationsIdRoute,
  TTenantRoute: TTenantRouteWithChildren,
  CompareIndexRoute: CompareIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
